#!/usr/bin/env bash
# Full disclosure cycle, live on Horizen testnet (chain 2651420).
#
# Not a simulation and not a fork. Every step below is a real transaction on a
# real chain, and the valuation dates are decided by the chain rather than by
# the test: the book is committed first, and only then can it be valued, so the
# script waits for the clock instead of warping it.
set -euo pipefail
cd "$(dirname "$0")"
export PATH="$HOME/.nargo/bin:$HOME/.bb:$PATH"

RPC="${HORIZEN_RPC:-https://horizen-testnet.rpc.caldera.xyz/http}"
# Keys never live in this repo. Drop DEPLOYER_PK in .env.local at the root,
# which is ignored, or export it before running.
[ -f ../.env.local ] && set -a && . ../.env.local && set +a
PK="${DEPLOYER_PK:?set DEPLOYER_PK in .env.local or the environment}"
ME=$(cast wallet address "$PK")
C=../contracts
Z=../zk
OUT=deployment-testnet.json
LOG=deployment-testnet.md

say() { printf '\n\033[1m== %s\033[0m\n' "$*" >&2; }
now() { cast block latest --rpc-url "$RPC" --json | python3 -c 'import sys,json;print(int(json.load(sys.stdin)["timestamp"],16))'; }
send() { # send <label> <to> <sig> [args...]
  local label=$1; shift
  local h
  h=$(cast send --rpc-url "$RPC" --private-key "$PK" --json "$@" | python3 -c 'import sys,json;d=json.load(sys.stdin);print(d["transactionHash"],int(d["gasUsed"],16))')
  local hash=${h%% *}; local gas=${h##* }
  printf '  %-26s %s  %s gas\n' "$label" "$hash" "$gas" >&2
  echo "| \`$label\` | [\`${hash:0:18}…\`](https://horizen-testnet.explorer.caldera.xyz/tx/$hash) | $gas |" >> "$LOG"
}
create() { # create <name> <path:Contract> [ctor args...]
  local name=$1 what=$2; shift 2
  local addr
  addr=$( (cd $C && forge create "$what" --rpc-url "$RPC" --private-key "$PK" --broadcast --json "$@") \
          | python3 -c 'import sys,json;print(json.load(sys.stdin)["deployedTo"])')
  printf '  %-26s %s\n' "$name" "$addr" >&2
  echo "| **$name** | [\`$addr\`](https://horizen-testnet.explorer.caldera.xyz/address/$addr) | |" >> "$LOG"
  echo "$addr"
}
pubinputs() { python3 -c "
import sys
d=open(sys.argv[1],'rb').read()
print('['+','.join('0x'+d[i*32:(i+1)*32].hex() for i in range(len(d)//32))+']')
" "$1"; }
proofhex() { python3 -c "print('0x'+open('$1','rb').read().hex())"; }
root_of() { (cd $Z/book_attest && nargo execute witness_probe 2>&1 | grep -o 'root: 0x[0-9a-f]*' | cut -d' ' -f2); }
waituntil() { local t=$1; while [ "$(now)" -lt "$t" ]; do sleep 5; done; }

echo "chain    $(cast chain-id --rpc-url "$RPC")"
echo "deployer $ME"
echo "balance  $(cast balance "$ME" --rpc-url "$RPC" --ether) ETH"

cat > "$LOG" <<EOF
# Agama on Horizen testnet, live deployment

Chain 2651420. Every row is a real transaction, not a fork or a simulation.
Generated by \`deploy/live-testnet.sh\`.

| Contract / call | Address or transaction | Gas |
| --- | --- | --- |
EOF

say "1. contracts"
USDC=$(create "TestUSDC"       src/TestUSDC.sol:TestUSDC)
VER=$(create  "HonkVerifier"   src/HonkVerifier.sol:HonkVerifier)
DVER=$(create "DeltaVerifier"  src/DeltaVerifier.sol:DeltaVerifier)
GEN=$(now)
REG=$(create  "CreditDisclosureRegistry" src/CreditDisclosureRegistry.sol:CreditDisclosureRegistry \
        --constructor-args "$VER" "$DVER" "$USDC" "$ME" "$GEN")
VAULT=$(create "AgamaCreditVault" src/AgamaCreditVault.sol:AgamaCreditVault \
        --constructor-args "$USDC" "$REG" "$ME")

say "2. wiring"
send "setVault"        "$REG" "setVault(address)" "$VAULT"
send "grant ORIGINATOR" "$REG" "grantRole(bytes32,address)" "$(cast keccak 'ORIGINATOR_ROLE')" "$ME"
send "grant VERIFIER"   "$REG" "grantRole(bytes32,address)" "$(cast keccak 'VERIFIER_ROLE')" "$ME"
send "vault ORIGINATOR"  "$VAULT" "grantRole(bytes32,address)" "$(cast keccak 'ORIGINATOR_ROLE')" "$ME"

say "3. commit the book before any cash moves"
T0=$(( $(now) + 150 ))
export AGAMA_AS_OF_0=$T0
python3 $Z/gen.py t0 >/dev/null
ROOT0=$(root_of)
echo "  as-of $T0, root $ROOT0"
send "commitBook" "$REG" "commitBook(bytes32)" "$ROOT0"
TC0=$(cast call "$REG" "bookCommittedAt(bytes32)(uint64)" "$ROOT0" --rpc-url "$RPC" | cut -d' ' -f1)
echo "  committed on-chain at $TC0"

say "4. fund the vault, post first loss, disburse"
send "mint tUSDC"     "$USDC"  "mint(address,uint256)" "$ME" 8000000000000
send "approve vault"  "$USDC"  "approve(address,uint256)" "$VAULT" 8000000000000
send "deposit 5.5m"   "$VAULT" "deposit(uint256,address)" 5500000000000 "$ME"
send "postFirstLoss"  "$VAULT" "postFirstLoss(uint256)" 500000000000
send "deploy 4.76m"   "$VAULT" "deploy(address,uint256,bytes32)" "$ME" 4760000000000 "$ROOT0"

say "5. prove and publish the risk surface"
(cd $Z/book_attest && nargo execute witness_live >/dev/null)
(cd $Z/book_attest && bb prove --scheme ultra_honk --oracle_hash keccak \
   -b target/book_attest.json -w target/witness_live.gz -o target/live_t0 >/dev/null)
echo "  waiting for the valuation date to arrive ($T0)"
waituntil "$T0"
send "publishSurface t0" "$REG" "publishSurface(bytes,bytes32[])" \
     "$(proofhex $Z/book_attest/target/live_t0/proof)" \
     "$(pubinputs $Z/book_attest/target/live_t0/public_inputs)"

say "6. collections arrive on-chain, short of the published calendar"
send "approve registry" "$USDC" "approve(address,uint256)" "$REG" 100000000000
send "recordCollection" "$REG" "recordCollection(uint256)" 12000000000

say "7. prove the revision descends honestly from the committed book"
T1=$(( $(now) + 150 ))
export AGAMA_AS_OF_1=$T1 AGAMA_PREV_COMMIT=$TC0
python3 $Z/gen.py delta >/dev/null
sed -i '' "s|^old_root = .*|old_root = \"$ROOT0\"|" $Z/book_delta/Prover.toml
(cd $Z/book_delta && nargo execute witness_live >/dev/null)
(cd $Z/book_delta && bb prove --scheme ultra_honk --oracle_hash keccak \
   -b target/book_delta.json -w target/witness_live.gz -o target/live_delta >/dev/null)
echo "  waiting for the revision date ($T1)"
waituntil "$T1"
send "commitRevision" "$REG" "commitRevision(bytes,bytes32[])" \
     "$(proofhex $Z/book_delta/target/live_delta/proof)" \
     "$(pubinputs $Z/book_delta/target/live_delta/public_inputs)"

say "8. publish the deteriorated surface"
python3 $Z/gen.py t1 >/dev/null
(cd $Z/book_attest && nargo execute witness_live1 >/dev/null)
(cd $Z/book_attest && bb prove --scheme ultra_honk --oracle_hash keccak \
   -b target/book_attest.json -w target/witness_live1.gz -o target/live_t1 >/dev/null)
send "publishSurface t1" "$REG" "publishSurface(bytes,bytes32[])" \
     "$(proofhex $Z/book_attest/target/live_t1/proof)" \
     "$(pubinputs $Z/book_attest/target/live_t1/public_inputs)"

say "9. exit queue"
SHARES=$(cast call "$VAULT" "balanceOf(address)(uint256)" "$ME" --rpc-url "$RPC" | cut -d' ' -f1)
send "requestRedeem" "$VAULT" "requestRedeem(uint256)" "$(python3 -c "print($SHARES//2)")"
send "settle"        "$VAULT" "settle()"

say "10. state readable by anyone"
read_u() { printf '  %-28s %s\n' "$1" "$(cast call "$2" "$3" ${4:-} --rpc-url "$RPC" | cut -d' ' -f1)" >&2; }
EPOCH=$(cast call "$REG" "currentEpoch()(uint64)" --rpc-url "$RPC" | cut -d' ' -f1)
read_u "impairedPrincipal"  "$REG"   "impairedPrincipal()(uint256)"
read_u "scheduled epoch $EPOCH"      "$REG"   "scheduledFor(uint64)(uint128)" "$EPOCH"
read_u "realized  epoch $EPOCH"      "$REG"   "realizedFor(uint64)(uint128)"  "$EPOCH"
read_u "performanceRatio"   "$REG"   "performanceRatio(uint64)(uint256)" "$EPOCH"
read_u "book revisions"     "$REG"   "bookHistoryLength()(uint256)"
read_u "totalAssets"        "$VAULT" "totalAssets()(uint256)"
read_u "firstLossRemaining" "$VAULT" "firstLossRemaining()(uint256)"
read_u "exposure"           "$VAULT" "exposure()(uint256)"

python3 - "$USDC" "$VER" "$DVER" "$REG" "$VAULT" "$ROOT0" "$GEN" \
        "$T0" "$T1" "$TC0" > "$OUT" <<'PY'
import json, sys
k = ["testUSDC","honkVerifier","deltaVerifier","registry","vault","genesisRoot","epochGenesis"]
d = dict(zip(k, sys.argv[1:8]))
d["chainId"] = 2651420
d["explorer"] = "https://horizen-testnet.explorer.caldera.xyz"
# The three clock values this run chose. A book root binds its valuation date,
# so without these the roots below cannot be regenerated after the fact:
#   AGAMA_AS_OF_0=... AGAMA_AS_OF_1=... AGAMA_PREV_COMMIT=... python3 ../zk/gen.py
d["reproduce"] = {
    "AGAMA_AS_OF_0": sys.argv[8],
    "AGAMA_AS_OF_1": sys.argv[9],
    "AGAMA_PREV_COMMIT": sys.argv[10],
}
print(json.dumps(d, indent=2))
PY
say "done"
cat "$OUT"
